= Centros Libres

== 01: Clara Visión

=== Presentación

La carretera Inter-Oceánica que conecta el Cusco con el Brasil, atraviesa en Madre de Dios una región del tamaño de Panamá, con la mayor biodiversidad del planeta y escasos 150 mil habitantes los cuales necesitan urgentemente modelos alternativos para alcanzar una prosperidad sustentable en armonía con el bosque.

Centro Libre Clara Visión se plantea como un espacio facilitador para la recuperación y puesta en valor de este conocimiento entendido como tecnología liberadora del ser humano.

=== Objetivo 

El establecimiento de una chacra-laboratorio para la experimentación, investigación y creatividad apoyada por tecnología libre  en todo ámbito desde la arquitectura, comunicación, generación de energía sostenible, agroforestería, como también la sostenibilidad alimentaria, ecosistémica mediante la gestión de cultivos y bosques. 

El centro abrirá al público ofreciendo talleres al tiempo de ofrecer una plataforma para  personas-investigadoras dispuestas a desarrollar y compartir su conocimiento en espíritu comunitario.