= Centros Libres

== 01: Clara Visión

=== Presentación 

Desde 2006 frecuentamos las regiones aledañas a la trifrontera Peru-Brasil-Bolivia y observamos grandes cambios en el territorio peruano, especialmente a lo largo de la nueva carretera Inter-Oceánica. Al mismo tiempo, nos enamoramos de la belleza natural y riqueza cultural de esta zona. Por ello sentimos el deseo de habitar en este lugar maravilloso, protegerlo, y llevar nuestras actividades de investigación y desarrollo, así como de difusión y promoción de tecnología libre, directamente ahí donde puede tener el mayor impacto medioambiental y social. Habiendo establecido alianzas con grupos y personas tanto en territorio peruano como brasilero y boliviano, 2015 es el año en que emprendemos esta misión. 

=== Objetivo 

El establecimiento de una finca laboratorio para la experimentación, la investigación y la creación ligada a la tecnología libre (arquitectura, comunicación, generación de energía sostenible) y la sostenibilidad (para cuerpo, ecosistemas, alimentos, cultivos, bosques), abierta al público, donde se realicen talleres y se reciban personas/investigadores dispuestas a compartir su conocimiento con las comunidades. 